# mange dependencies with brew https://brew.sh/

brew "asdf"                 # Extendable version manager with support for
                            # Ruby, Node.js, Erlang & more
                            # https://asdf-vm.com/
brew "exercism"             # code learning platform

cask "spectacle"            # screen realestate management

brew "postgresql@15"        # Object-relational database system
                            # https://www.postgresql.org/
brew "postgis"              # Adds support for geographic objects to PostgreSQL
                            # https://postgis.net/
                            # postgis: stable 3.3.4 (bottled), HEAD