# mange dependencies with brew https://brew.sh/

brew "asdf"                 # Extendable version manager with support for
                            # Ruby, Node.js, Erlang & more
                            # https://asdf-vm.com/
brew "exercism"             # code learning platform

cask "spectacle"            # screen realestate management